services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
      - alertmanager
    ports:
      - "${GF_PORT:-3000}:3000"
    environment:
      GF_SERVER_ROOT_URL: ${GF_SERVER_ROOT_URL}
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
      GF_SERVER_HTTP_PORT: ${GF_PORT:-3000}
      GF_GITHUB_PLUGINS: "https://github.com/grafana/grafana-infinity-datasource/releases/download/v2.11.4/yesoreyeram-infinity-datasource-2.11.4.zip"
      PROMETHEUS_URL: "http://${PROMETHEUS_TARGET:-localhost:9090}"
      ALERTMANAGER_URL: "http://${ALERTMANAGER_TARGET:-localhost:9093}"
      WALRUS_NODE_TARGET: ${WALRUS_NODE_TARGET:-}
      WALRUS_AGGREGATOR_TARGET: ${WALRUS_AGGREGATOR_TARGET:-}
      WALRUS_PUBLISHER_TARGET: ${WALRUS_PUBLISHER_TARGET:-}
      WALRUS_NODE_URL: ${WALRUS_NODE_URL}
    volumes:
      - ./grafana/dashboards:/tmp/dashboards
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/entrypoint.sh:/entrypoint.sh
    entrypoint: ["/entrypoint.sh"]

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    command:
      - '--web.listen-address=:${PROMETHEUS_PORT:-9090}'
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"
    volumes:
      - prometheus_data:/prometheus
      - ./prometheus/entrypoint.sh:/entrypoint.sh
      - ./prometheus/rules:/etc/prometheus/rules
    environment:
      PROMETHEUS_TARGET: ${PROMETHEUS_TARGET:-localhost:9090}
      WALRUS_NODE_TARGET: ${WALRUS_NODE_TARGET:-}
      WALRUS_AGGREGATOR_TARGET: ${WALRUS_AGGREGATOR_TARGET:-}
      WALRUS_PUBLISHER_TARGET: ${WALRUS_PUBLISHER_TARGET:-}
      ALERTMANAGER_TARGET: ${ALERTMANAGER_TARGET:-localhost:9093}
    entrypoint: ["/entrypoint.sh"]

  alertmanager:
    image: prom/alertmanager:latest
    container_name: alertmanager
    command:
      - '--web.listen-address=:${ALERTMANAGER_PORT:-9093}'
      - '--cluster.listen-address='
    volumes:
      - ./alertmanager/entrypoint.sh:/entrypoint.sh
    ports:
      - "${ALERTMANAGER_PORT:-9093}:9093"
    environment:
      ALERTMANAGER_DEFAULT_WEBHOOK_PORT: "${ALERTMANAGER_DEFAULT_WEBHOOK_PORT:-3001}"
      PAGERDUTY_INTEGRATION_KEY: "${PAGERDUTY_INTEGRATION_KEY:-}"
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
      DISCORD_WEBHOOK_URL: "${DISCORD_WEBHOOK_URL:-}"
      SLACK_WEBHOOK_URL: "${SLACK_WEBHOOK_URL:-}"
    entrypoint: ["/entrypoint.sh"]

volumes:
  grafana_data:
    driver: local
  prometheus_data:
    driver: local
