{
 "title": "Walrus Publisher",
 "description": "This dashboard provides a comprehensive view of metrics related to Publisher services, which play a crucial role in storing blobs to Walrus. Publishers ensure that data is efficiently and reliably written into the decentralized storage network.",
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  { "title": "Publisher Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the Walrus Publisher.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_build_info{service=\"publisher\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "Displays the current epoch number in the Walrus network, indicating the network's operational state.",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_current_epoch{service=\"publisher\"})"
    }
   ]
  },
  {
   "title": "Epoch State Timeline",
   "type": "timeseries",
   "description": "Displays the timeline of Walrus Publisher epoch states, highlighting transitions between inactive (0) and active (1) statuses.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_current_epoch_state{service=\"publisher\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Wal Refills",
   "type": "timeseries",
   "description": "Visualizes the total number of wal refills over time and their cumulative counter.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(wal_refill{service=\"publisher\"}[1h])",
     "legendFormat": "Rate of Refills (per hour)"
    },
    {
     "expr": "wal_refill{service=\"publisher\"}",
     "legendFormat": "Cumulative Refills"
    }
   ]
  },
  {
   "title": "Gas Refills",
   "type": "timeseries",
   "description": "Visualizes the total number of gas refills over time and their cumulative counter.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "increase(gas_refill{service=\"publisher\"}[1h])",
     "legendFormat": "Rate of Refills (per hour)"
    },
    {
     "expr": "gas_refill{service=\"publisher\"}",
     "legendFormat": "Cumulative Refills"
    }
   ]
  },
  { "title": "Span Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Latency Distribution",
   "type": "timeseries",
   "description": "Displays the latency distribution for spans in the Publisher service, categorized by span names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_name) (rate(tracing_span_latencies_bucket{service=\"publisher\"}[5m])))",
     "legendFormat": "95th percentile - {{span_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Displays the average latency for spans in the Publisher service.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "tracing_span_latencies_sum{service=\"publisher\"} / tracing_span_latencies_count{service=\"publisher\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 } },
  {
   "title": "HTTP Request Duration Over Time",
   "type": "timeseries",
   "description": "Displays the duration of HTTP requests for different routes and their status codes in the Walrus Publisher over time. The right column in the legend shows the HTTP method, route (Name), and status code (Status).",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"publisher\"}[5m]) / rate(http_request_duration_seconds_count{service=\"publisher\"}[5m])",
     "legendFormat": "Name: {{method}} {{route}} {{status_code}}"
    }
   ]
  }
 ]
}