{
 "title": "Walrus Aggregator",
 "description": "This dashboard provides a comprehensive view of metrics related to Aggregators, which are clients that play a crucial role in reconstructing blobs from slivers. Aggregators make these reconstructed blobs accessible to end users via traditional web2 technologies like HTTP.",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  { "title": "Aggregator Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the Walrus Aggregator.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_build_info{service=\"aggregator\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Span Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Latency Distribution",
   "type": "timeseries",
   "description": "Displays the latency distribution for spans in the Aggregator service, categorized by span names.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by(le, span_name) (rate(tracing_span_latencies_bucket{service=\"aggregator\"}[$__rate_interval])))",
     "legendFormat": "95th percentile - {{span_name}}"
    }
   ]
  },
  {
   "title": "Average Latency",
   "type": "timeseries",
   "description": "Displays the average latency for spans in the Aggregator service.",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "tracing_span_latencies_sum{service=\"aggregator\"} / tracing_span_latencies_count{service=\"aggregator\"}",
     "legendFormat": "{{span_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "HTTP Request Duration Over Time",
   "type": "timeseries",
   "description": "Displays the duration of HTTP requests for different routes and their status codes in the Walrus Aggregator over time. The right column in the legend shows the HTTP method, route (Name), and status code (Status).",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"aggregator\"}[$__rate_interval]) / rate(http_request_duration_seconds_count{service=\"aggregator\"}[$__rate_interval])",
     "legendFormat": "Name: {{method}} {{route}} {{status_code}}"
    }
   ]
  }
 ]
}