{
 "title": "Walrus Storage Node",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Node Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Build Version",
   "type": "stat",
   "description": "Shows the current build version of the Walrus Storage Node.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_build_info{service=\"storage_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Chain ID",
   "type": "stat",
   "description": "Displays the chain identifier of the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{service=\"storage_node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Epoch",
   "type": "stat",
   "description": "Displays the current epoch number in the Walrus network, indicating the network's operational state.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_current_epoch{service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Displays the total uptime of the Walrus Storage Node in seconds, indicating its operational status.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uptime{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Epoch State Timeline",
   "type": "timeseries",
   "description": "Displays the timeline of Walrus Storage Node epoch states, highlighting transitions between inactive (0) and active (1) statuses.",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_current_epoch_state{service=\"storage_node\"}",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Uptime Timeline",
   "type": "timeseries",
   "description": "Displays the uptime trend status of the Walrus Storage Node. Green indicates uptime is increasing, and red indicates it is not.",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(uptime{service=\"storage_node\"}[1m])",
     "legendFormat": "{{process}}"
    }
   ]
  },
  { "title": "Checkpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "Checkpoint Lag",
   "type": "stat",
   "description": "Displays the current checkpoint lag between the local store and the full node in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(checkpoint_downloader_checkpoint_lag{service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Active Workers",
   "type": "stat",
   "description": "Displays the number of active workers in the checkpoint downloader's worker pool for the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "checkpoint_downloader_num_workers{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Total Downloaded Checkpoints",
   "type": "stat",
   "description": "Displays the total number of checkpoints downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_processor_total_downloaded_checkpoints{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Latest Downloaded Checkpoint",
   "type": "stat",
   "description": "Displays the latest full checkpoint downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "event_processor_latest_downloaded_checkpoint{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Checkpoint Lag Over Time",
   "type": "timeseries",
   "description": "Displays the maximum checkpoint lag over time in the Walrus network, helping to identify delays between local store and full node.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(checkpoint_downloader_checkpoint_lag{service=\"storage_node\"})",
     "legendFormat": "Latest Lag"
    }
   ]
  },
  {
   "title": "Checkpoint Download Over Time",
   "type": "timeseries",
   "description": "Shows the timeline of the latest full checkpoint downloaded by the event processor in the Walrus network.",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "event_processor_latest_downloaded_checkpoint{service=\"storage_node\"}",
     "legendFormat": "Latest Checkpoint"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 } },
  {
   "title": "Pending Events",
   "type": "stat",
   "description": "Displays the number of Walrus events currently in the pending state.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"pending\", service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Persisted Events",
   "type": "stat",
   "description": "Displays the number of Walrus events currently in the persisted state.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"persisted\", service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Average Event Processing Time",
   "type": "bargauge",
   "description": "Displays the average processing time for each event type in the Walrus network, with color thresholds for performance monitoring.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (event_type) (rate(walrus_event_process_duration_seconds_sum{service=\"storage_node\"}[5m])) / sum by (event_type) (rate(walrus_event_process_duration_seconds_count{service=\"storage_node\"}[5m]))",
     "legendFormat": "{{event_type}}"
    }
   ]
  },
  {
   "title": "Persisted Event Cursor Progress",
   "type": "timeseries",
   "description": "Displays the progress of persisted events in the Walrus network over time.",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "walrus_event_cursor_progress{state=\"persisted\", service=\"storage_node\"}",
     "legendFormat": "Persisted Events"
    }
   ]
  },
  { "title": "Shards & Slivers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Total Metadata Blob Size Processed",
   "type": "stat",
   "description": "Displays the total unencoded size of all uploaded blobs based on metadata.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_uploaded_metadata_unencoded_blob_bytes_sum{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Shards Owned",
   "type": "stat",
   "description": "Displays the number of shards currently owned by this node in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(walrus_shards_owned{service=\"storage_node\"})"
    }
   ]
  },
  {
   "title": "Total Metadata Operations",
   "type": "stat",
   "description": "Displays the total count of metadata operations (stored and retrieved) in the Walrus network.",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_metadata_stored_total + walrus_metadata_retrieved_total{service=\"storage_node\"}",
     "legendFormat": "Total Metadata Operations"
    }
   ]
  },
  {
   "title": "Total Sliver Operations",
   "type": "stat",
   "description": "Displays the total count of sliver operations (retrieved and stored) across all types (primary and secondary).",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "walrus_slivers_retrieved_total{service=\"storage_node\"} + walrus_slivers_stored_total{service=\"storage_node\"}"
    }
   ]
  },
  {
   "title": "Sliver Operations Rate",
   "type": "timeseries",
   "description": "Displays the rate of sliver operations (retrieved and stored) over time, separated by type (primary or secondary).",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_slivers_retrieved_total{sliver_type=\"primary\", service=\"storage_node\"}[5m])",
     "legendFormat": "Retrieved - Primary"
    },
    {
     "expr": "rate(walrus_slivers_retrieved_total{sliver_type=\"secondary\", service=\"storage_node\"}[5m])",
     "legendFormat": "Retrieved - Secondary"
    },
    {
     "expr": "rate(walrus_slivers_stored_total{sliver_type=\"primary\", service=\"storage_node\"}[5m])",
     "legendFormat": "Stored - Primary"
    },
    {
     "expr": "rate(walrus_slivers_stored_total{sliver_type=\"secondary\", service=\"storage_node\"}[5m])",
     "legendFormat": "Stored - Secondary"
    }
   ]
  },
  {
   "title": "Rates of Metadata Operations",
   "type": "timeseries",
   "description": "Displays the rate of metadata operations (stored and retrieved) over time, enabling a comparison of storage and retrieval rates.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_metadata_stored_total{service=\"storage_node\"}[5m])",
     "legendFormat": "Metadata Stored Rate"
    },
    {
     "expr": "rate(walrus_metadata_retrieved_total{service=\"storage_node\"}[5m])",
     "legendFormat": "Metadata Retrieval Rate"
    }
   ]
  },
  {
   "title": "Rate of Storage Confirmations Issued",
   "type": "timeseries",
   "description": "Displays the rate at which storage confirmations are issued over time in the Walrus network.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(walrus_storage_confirmations_issued_total[5m])",
     "legendFormat": "Confirmations"
    }
   ]
  },
  {
   "title": "Block Cache Hit Rate Over Time",
   "type": "timeseries",
   "description": "Shows the block cache hit rate for each column family in the Walrus Storage Node over time, helping identify trends and patterns in cache usage.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "hits" } },
   "targets": [
    {
     "expr": "rate(block_cache_hit_count{service=\"storage_node\"}[5m])",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Get Read Bytes Over Time",
   "type": "timeseries",
   "description": "Shows the total bytes read for values returned by Get operations in the Walrus Storage Node over time. This metric highlights read activity by column family.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(get_read_bytes{service=\"storage_node\"}[5m]) / (1024 * 1024)",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Block Read Rate Over Time",
   "type": "timeseries",
   "description": "Shows the block read rate for each column family in the Walrus Storage Node, indicating the volume of data being read from the file system over time. Useful for analyzing potential bottlenecks caused by large blocks or queries.",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(block_read_byte{service=\"storage_node\"}[5m]) / (1024 * 1024)",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  {
   "title": "Block Read Count Over Time",
   "type": "timeseries",
   "description": "Shows the block read count for each column family in the Walrus Storage Node over time. This metric highlights instances of direct file system reads, indicating potential cache misses or scenarios where the block cache is disabled.",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rate(block_read_count{service=\"storage_node\"}[5m])",
     "legendFormat": "{{cf_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 65 } },
  {
   "title": "HTTP Request Duration Over Time",
   "type": "timeseries",
   "description": "Displays the duration of HTTP requests for different routes and their status codes in the Walrus Storage Node over time. The right column in the legend shows the HTTP method, route (Name), and status code (Status).",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{service=\"storage_node\"}[5m]) / rate(http_request_duration_seconds_count{service=\"storage_node\"}[5m])",
     "legendFormat": "Name: {{method}} {{route}} {{status_code}}"
    }
   ]
  }
 ]
}